// auth
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_LOADING_INDICATOR = "LOGIN_LOADING_INDICATOR";
export const LOGOUT = "LOGOUT";
export const DISPATCH_ERROR = "DISPATCH_ERROR";
export const CLEAR_ERROR_STATE = "CLEAR_ERROR_STATE";

//contestants Type
export const GET_CONTESTANTS = "GET_CONTESTANTS";
export const GET_CONTESTANTS_SUCCESS = "GET_CONTESTANTS_SUCCESS";
export const GET_CONTESTANTS_FAILURE = "GET_CONTESTANTS_FAILURE";
export const GET_CONTESTANT_REQUEST = "GET_CONTESTANT_REQUEST";
export const GET_CONTESTANT_SUCCESS = "GET_CONTESTANT_SUCCESS";
export const GET_CONTESTANT_FAILURE = "GET_CONTESTANT_FAILURE";
export const ADD_CONTESTANT_REQUEST = "ADD_CONTESTANT_REQUEST";
export const ADD_CONTESTANT_SUCCESS = "ADD_CONTESTANT_SUCCESS";
export const ADD_CONTESTANT_FAILURE = "ADD_CONTESTANT_FAILURE";
export const UPDATE_CONTESTANT_REQUEST = "UPDATE_CONTESTANT_REQUEST";
export const UPDATE_CONTESTANT_SUCCESS = "UPDATE_CONTESTANT_SUCCESS";
export const UPDATE_CONTESTANT_FAILURE = "UPDATE_CONTESTANT_FAILURE";

export const GET_CONTESTANTS_LOADING_INDICATOR =
  "GET_CONTESTANTS_LOADING_INDICATOR";

export const MANAGE_CONTESTANT_REQUEST = "MANAGE_CONTESTANT_REQUEST";
export const MANAGE_CONTESTANT_SUCCESS = "MANAGE_CONTESTANT_SUCCESS";
export const MANAGE_CONTESTANT_FAILURE = "MANAGE_CONTESTANT_FAILURE";
export const MANAGE_CONTESTANT_LOADING_INDICATOR =
  "MANAGE_CONTESTANT_LOADING_INDICATOR";

//eviction Type
export const GET_EVICTIONS_REQUEST = "GET_EVICTIONS_REQUEST";
export const GET_EVICTION_REQUEST = "GET_EVICTION_REQUEST";
export const GET_EVICTION_SUCCESS = "GET_EVICTION_SUCCESS";
export const GET_EVICTIONS_SUCCESS = "GET_EVICTIONS_SUCCESS";
export const GET_EVICTIONS_FAILURE = "GET_EVICTIONS_FAILURE";
export const GET_EVICTION_FAILURE = "GET_EVICTION_FAILURE";
export const ADD_EVICTION_REQUEST = "ADD_EVICTION_REQUEST";
export const UPDATE_EVICTION_REQUEST = "UPDATE_EVICTION_REQUEST";
export const CHANGE_EVICTION_STATUS_REQUEST = "CHANGE_EVICTION_STATUS_REQUEST";
export const ADD_EVICTION_SUCCESS = "ADD_EVICTION_SUCCESS";
export const UPDATE_EVICTION_SUCCESS = "UPDATE_EVICTION_SUCCESS";
export const CHANGE_EVICTION_STATUS_SUCCESS = "CHANGE_EVICTION_STATUS_SUCCESS";
export const ADD_EVICTION_FAILURE = "ADD_EVICTION_FAILURE";
export const ADD_EVICTION_LOADING_INDICATOR = "ADD_EVICTION_LOADING_INDICATOR";
export const UPDATE_EVICTION_FAILURE = "UPDATE_EVICTION_FAILURE";
export const UPDATE_EVICTION_LOADING_INDICATOR =
  "UPDATE_EVICTION_LOADING_INDICATOR";
export const CHANGE_EVICTION_STATUS_FAILURE = "CHANGE_EVICTION_STATUS_FAILURE";
export const CHANGE_EVICTION_STATUS_LOADING_INDICATOR =
  "CHANGE_EVICTION_STATUS_LOADING_INDICATOR";
export const GET_CURRENT_EVICTION_REQUEST = "GET_CURRENT_EVICTION_REQUEST";
export const GET_CURRENT_EVICTION_SUCCESS = "GET_CURRENT_EVICTION_SUCCESS";
export const GET_CURRENT_EVICTION_FAILURE = "GET_CURRENT_EVICTION_FAILURE";
export const GET_CURRENT_EVICTION_LOADING_INDICATOR =
  "GET_CURRENT_EVICTION_LOADING_INDICATOR";

// Vote Settings

export const GET_VOTE_SETTINGS_REQUEST = "GET_VOTE_SETTINGS_REQUEST";
export const GET_VOTE_SETTINGS_SUCCESS = "GET_VOTE_SETTINGS_SUCCESS";
export const GET_VOTE_SETTINGS_FAILURE = "GET_VOTE_SETTINGS_FAILURE";
export const GET_VOTE_SETTINGS_LOADING_INDICATOR =
  "GET_VOTE_SETTINGS_LOADING_INDICATOR";

export const UPDATE_VOTE_SETTINGS_REQUEST = "UPDATE_VOTE_SETTINGS_REQUEST";
export const UPDATE_VOTE_SETTINGS_SUCCESS = "UPDATE_VOTE_SETTINGS_SUCCESS";
export const UPDATE_VOTE_SETTINGS_FAILURE = "UPDATE_VOTE_SETTINGS_FAILURE";
export const UPDATE_VOTE_SETTINGS_LOADING_INDICATOR =
  "UPDATE_VOTE_SETTINGS_LOADING_INDICATOR";

export const GET_DASHBOARD_STARTS_REQUEST = "GET_DASHBOARD_STARTS_REQUEST";
export const GET_DASHBOARD_STARTS_SUCCESS = "GET_DASHBOARD_STARTS_SUCCESS";
export const GET_DASHBOARD_STARTS_FAILURE = "GET_DASHBOARD_STARTS_FAILURE";
export const GET_DASHBOARD_STARTS_LOADING_INDICATOR =
  "DASHBOARD_STARTS_LOADING_INDICATOR";

export const GET_WALLET_HISTORY_REQUEST = "GET_WALLET_HISTORY_REQUEST";
export const GET_WALLET_HISTORY_SUCCESS = "GET_WALLET_HISTORY_SUCCESS";
export const GET_WALLET_HISTORY_FAILURE = "GET_WALLET_HISTORY_FAILURE";
export const GET_WALLET_HISTORY_LOADING_INDICATOR =
  "GET_WALLET_HISTORY_LOADING_INDICATOR";
// Misc
export const GET_BANKS_REQUEST = "GET_BANKS_REQUEST";
export const GET_BANKS_SUCCESS = "GET_BANKS_SUCCESS";
export const GET_BANKS_FAILURE = "GET_BANKS_FAILURE";
export const GET_BANKS_LOADING_INDICATOR = "GET_BANKS_LOADING_INDICATOR";

// Wallet
export const GET_WALLET_DETAILS_REQUEST = "GET_WALLET_DETAILS_REQUEST";
export const GET_WALLET_DETAILS_SUCCESS = "GET_WALLET_DETAILS_SUCCESS";
export const GET_WALLET_DETAILS_FAILURE = "GET_WALLET_DETAILS_FAILURE";
export const GET_WALLET_DETAILS_LOADING_INDICATOR =
  "GET_WALLET_DETAILS_LOADING_INDICATOR";

export const SAVE_WALLET_DETAILS_REQUEST = "SAVE_WALLET_DETAILS_REQUEST";
export const SAVE_WALLET_DETAILS_SUCCESS = "SAVE_WALLET_DETAILS_SUCCESS";
export const SAVE_WALLET_DETAILS_FAILURE = "SAVE_WALLET_DETAILS_FAILURE";
export const SAVE_WALLET_DETAILS_LOADING_INDICATOR =
  "SAVE_WALLET_DETAILS_LOADING_INDICATOR";

export const SET_WALLET_PIN_REQUEST = "SET_WALLET_PIN_REQUEST";
export const SET_WALLET_PIN_SUCCESS = "SET_WALLET_PIN_SUCCESS";
export const SET_WALLET_PIN_FAILURE = "SET_WALLET_PIN_FAILURE";
export const SET_WALLET_PIN_LOADING_INDICATOR =
  "SET_WALLET_PIN_LOADING_INDICATOR";

export const WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAILURE = "WITHDRAWAL_FAILURE";
export const WITHDRAWAL_LOADING_INDICATOR = "WITHDRAWAL_LOADING_INDICATOR";

// Evicted contestant
export const GET_EVICTED_CONTESTANTS_REQUEST =
  "GET_EVICTED_CONTESTANTS_REQUEST";
export const GET_EVICTED_CONTESTANTS_SUCCESS =
  "GET_EVICTED_CONTESTANTS_SUCCESS";
export const GET_EVICTED_CONTESTANTS_FAILURE =
  "GET_EVICTED_CONTESTANTS_FAILURE";
export const GET_EVICTED_CONTESTANTS_LOADING_INDICATOR =
  "GET_EVICTED_CONTESTANTS_LOADING_INDICATOR";
